### ISSUE TITLE
wrong infos in package.json

### ISSUE THREAD

**Issue by GlennCavarle** [libre-informatique/LiftJS#1]
There are still references to the project `front-online-choice` (e.g. name, repository, ...).
The "main" entry should probably point to the `dist/liftJs.min.js`.

**Comment by PapsOu** [comment]
Do you have any example of unexpected references to other projects ?

About the main entry point, we should build a new repository maybe called « LiftJsProjectSkeleton » that will have a base index.html in order to remove the index.html from LiftJS repository. In this future skeleton, the entry point would be `dist/liftJs.min.js` as mentioned in this issue.

**Comment by GlennCavarle** [comment]
> Do you have any example of unexpected references to other projects ?

What do you mean?
What I was saying is that the `name` and `repository` entries in ` package.json` have to point to "LiftJS" and https://github.com/libre-informatique/LiftJS, respectively, not to `front-online-choice`.

As you say, a clearer distinction should be made between the library and the example app. Maybe, a simple `example` directory would be sufficient as a first step.

In the end, LiftJS could be installed using npm or bower, even if it is not registered, like below:
`npm install libre-informatique/LiftJS`
`bower install https://github.com/libre-informatique/LiftJS`

**Comment by PapsOu** [comment]
Fixed package.json in e96d9429da4283b600c6a2512f01e4eff160ee2b

We will nedd to plan portage of this lib for npm (post-install script to move LiftJS folder into user's project folder, exporting only dist, etc.)
